export enum ColorEnum {
  PRIMARY = "primary",
  SECONDARY = "secondary",
  SUCCESS = "success",
  WARNING = "warning",
  BASE = "base",
  CONTRAST = "contrast",
  GRASS = "grass",
  ELECTRIC = "electric",
  FAIRY = "fairy",
  FIRE = "fire",
  NORMAL = "normal",
  FIGHTER = "fighter",
  POISON = "poison",
  DRAGON = "dragon",
  STEEL = "steel",
  WATER = "water",
  DARK = "dark",
}

export const COLOR_TEXT_MAP = {
  [ColorEnum.BASE]: "text-system-800",
  [ColorEnum.CONTRAST]: "text-system-600",
  [ColorEnum.PRIMARY]: "text-primary",
  [ColorEnum.SECONDARY]: "text-secondary",
  [ColorEnum.SUCCESS]: "text-success",
  [ColorEnum.WARNING]: "text-warning",
  [ColorEnum.GRASS]: "text-types-grass",
  [ColorEnum.ELECTRIC]: "text-types-electric",
  [ColorEnum.FAIRY]: "text-types-fairy",
  [ColorEnum.FIRE]: "text-types-fire",
  [ColorEnum.NORMAL]: "text-types-normal",
  [ColorEnum.FIGHTER]: "text-types-fighter",
  [ColorEnum.POISON]: "text-types-poison",
  [ColorEnum.DRAGON]: "text-types-dragon",
  [ColorEnum.STEEL]: "text-types-steel",
  [ColorEnum.WATER]: "text-types-water",
  [ColorEnum.DARK]: "text-types-dark",
};

export const COLOR_BG_MAP = {
  [ColorEnum.BASE]: "bg-system-800",
  [ColorEnum.CONTRAST]: "bg-system-600",
  [ColorEnum.PRIMARY]: "bg-primary",
  [ColorEnum.SECONDARY]: "bg-secondary",
  [ColorEnum.SUCCESS]: "bg-success",
  [ColorEnum.WARNING]: "bg-warning",
  [ColorEnum.GRASS]: "bg-types-grass",
  [ColorEnum.ELECTRIC]: "bg-types-electric",
  [ColorEnum.FAIRY]: "bg-types-fairy",
  [ColorEnum.FIRE]: "bg-types-fire",
  [ColorEnum.NORMAL]: "bg-types-normal",
  [ColorEnum.FIGHTER]: "bg-types-fighter",
  [ColorEnum.POISON]: "bg-types-poison",
  [ColorEnum.DRAGON]: "bg-types-dragon",
  [ColorEnum.STEEL]: "bg-types-steel",
  [ColorEnum.WATER]: "bg-types-water",
  [ColorEnum.DARK]: "bg-types-dark",
};